use std::sync::LazyLock;

use crate::{
    error::{Result, ResultLogExt},
    event_manager,
};
use seelen_core::system_state::{Color, UIColors};
use windows::{
    Foundation::TypedEventHandler,
    UI::ViewManagement::{UIColorType, UISettings},
};
use windows_core::IInspectable;

fn winrt_to_self(color: windows::UI::Color) -> Color {
    Color {
        r: color.R,
        g: color.G,
        b: color.B,
        a: color.A,
    }
}

fn srgb_to_linear(c: f64) -> f64 {
    if c <= 0.04045 {
        c / 12.92
    } else {
        ((c + 0.055) / 1.055).powf(2.4)
    }
}

fn linear_to_srgb(c: f64) -> f64 {
    if c <= 0.0031308 {
        c * 12.92
    } else {
        1.055 * c.powf(1.0 / 2.4) - 0.055
    }
}

/// Returns (L, C, H) in OKLCH — L in [0,1], C ≥ 0, H in [0°,360°).
fn rgb_to_oklch(r: u8, g: u8, b: u8) -> (f64, f64, f64) {
    let r = srgb_to_linear(r as f64 / 255.0);
    let g = srgb_to_linear(g as f64 / 255.0);
    let b = srgb_to_linear(b as f64 / 255.0);

    let l = 0.4121656120 * r + 0.5362752080 * g + 0.0514575653 * b;
    let m = 0.2118591070 * r + 0.6807189584 * g + 0.1074065790 * b;
    let s = 0.0883097947 * r + 0.2818474174 * g + 0.6302613616 * b;

    let l_ = l.cbrt();
    let m_ = m.cbrt();
    let s_ = s.cbrt();

    let ok_l = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_;
    let ok_a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_;
    let ok_b = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_;

    let c = (ok_a * ok_a + ok_b * ok_b).sqrt();
    let h = ok_b.atan2(ok_a).to_degrees();
    let h = if h < 0.0 { h + 360.0 } else { h };

    (ok_l, c, h)
}

fn oklch_to_rgb(l: f64, c: f64, h: f64) -> (u8, u8, u8) {
    let h_rad = h.to_radians();
    let ok_a = c * h_rad.cos();
    let ok_b = c * h_rad.sin();

    let l_ = l + 0.3963377774 * ok_a + 0.2158037573 * ok_b;
    let m_ = l - 0.1055613458 * ok_a - 0.0638541728 * ok_b;
    let s_ = l - 0.0894841775 * ok_a - 1.2914855480 * ok_b;

    let lms_l = l_ * l_ * l_;
    let lms_m = m_ * m_ * m_;
    let lms_s = s_ * s_ * s_;

    let r = 4.0767416621 * lms_l - 3.3077115913 * lms_m + 0.2309699292 * lms_s;
    let g = -1.2684380046 * lms_l + 2.6097574011 * lms_m - 0.3413193965 * lms_s;
    let b = -0.0041960863 * lms_l - 0.7034186147 * lms_m + 1.7076147010 * lms_s;

    (
        (linear_to_srgb(r.clamp(0.0, 1.0)) * 255.0).round() as u8,
        (linear_to_srgb(g.clamp(0.0, 1.0)) * 255.0).round() as u8,
        (linear_to_srgb(b.clamp(0.0, 1.0)) * 255.0).round() as u8,
    )
}

/// Generates a 32-byte AccentPalette for the Windows registry.
/// 8 colors × 4 bytes (RGBA), ordered: accent_darkest … accent_lightest, complement.
/// Shades are generated by interpolating OKLCH lightness (perceptually uniform),
/// from 0.15 → base_L (indices 0-3) and base_L → 0.85 (indices 3-6).
/// The complement (index 7) keeps the same L and C with hue rotated 180°.
fn generate_accent_palette(color: seelen_core::system_state::Color) -> UIColors {
    let (l, c, h) = rgb_to_oklch(color.r, color.g, color.b);
    let mut palette = [0u8; 32];

    for i in 0usize..7 {
        // index 0 = lightest (accent_lightest), index 6 = darkest (accent_darkest)
        let j = 6 - i;
        let step_l = if j <= 3 {
            let t = j as f64 / 3.0;
            0.18 + t * (l - 0.18)
        } else {
            let t = (j - 3) as f64 / 3.0;
            l + t * (0.90 - l)
        };

        let (r, g, b) = oklch_to_rgb(step_l, c, h);
        let off = i * 4;
        palette[off] = r;
        palette[off + 1] = g;
        palette[off + 2] = b;
        palette[off + 3] = color.a;
    }

    // Complement: hue rotated 180°
    let (r, g, b) = oklch_to_rgb(l, c, (h + 180.0) % 360.0);
    palette[28] = r;
    palette[29] = g;
    palette[30] = b;
    palette[31] = color.a;

    UIColors::from_bytes(&palette)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SystemSettingsEvent {
    ColorChanged,
    TextScaleChanged,
}

pub struct SystemSettings {
    settings: UISettings,
    color_event_token: Option<i64>,
    text_scale_event_token: Option<i64>,
}

unsafe impl Send for SystemSettings {}

event_manager!(SystemSettings, SystemSettingsEvent);

impl SystemSettings {
    pub fn instance() -> &'static Self {
        static SYSTEM_SETTINGS: LazyLock<SystemSettings> = LazyLock::new(|| {
            let mut settings = SystemSettings::new();
            settings.init().log_error();
            settings
        });
        &SYSTEM_SETTINGS
    }

    fn new() -> Self {
        Self {
            settings: UISettings::new().expect("Failed to create UISettings"),
            color_event_token: None,
            text_scale_event_token: None,
        }
    }

    fn init(&mut self) -> Result<()> {
        // Register color change event
        // Windows-rs clones the handler internally, so we don't need to store it
        let color_token = self
            .settings
            .ColorValuesChanged(&TypedEventHandler::new(Self::internal_on_colors_change))?;
        self.color_event_token = Some(color_token);

        // Register text scale change event
        let text_scale_token = self
            .settings
            .TextScaleFactorChanged(&TypedEventHandler::new(Self::internal_on_text_scale_change))?;
        self.text_scale_event_token = Some(text_scale_token);

        Ok(())
    }

    fn internal_on_colors_change(
        _listener: windows_core::Ref<UISettings>,
        _args: windows_core::Ref<IInspectable>,
    ) -> windows_core::Result<()> {
        let _ = Self::event_tx().send(SystemSettingsEvent::ColorChanged);
        Ok(())
    }

    fn internal_on_text_scale_change(
        _listener: windows_core::Ref<UISettings>,
        _args: windows_core::Ref<IInspectable>,
    ) -> windows_core::Result<()> {
        let _ = Self::event_tx().send(SystemSettingsEvent::TextScaleChanged);
        Ok(())
    }

    pub fn set_accent_color(color: seelen_core::system_state::Color) -> Result<()> {
        use windows::Win32::{
            Foundation::{LPARAM, WPARAM},
            UI::WindowsAndMessaging::{SendNotifyMessageW, HWND_BROADCAST, WM_SETTINGCHANGE},
        };
        use windows_core::w;
        use winreg::{enums::HKEY_CURRENT_USER, RegKey};

        log::info!(
            "Setting accent color to #{:02X}{:02X}{:02X}{:02X}",
            color.r,
            color.g,
            color.b,
            color.a
        );

        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        let key = hkcu.open_subkey_with_flags(
            r"Software\Microsoft\Windows\CurrentVersion\Explorer\Accent",
            winreg::enums::KEY_SET_VALUE,
        )?;
        // Registry stores the accent color as 0xAABBGGRR
        let dword: u32 = u32::from_be_bytes([color.a, color.b, color.g, color.r]);
        key.set_value("AccentColor", &dword)?;
        key.set_value("AccentColorMenu", &dword)?;
        key.set_value("StartColorMenu", &dword)?;

        let palette = generate_accent_palette(color);
        key.set_raw_value(
            "AccentPalette",
            &winreg::RegValue {
                bytes: palette.to_bytes().to_vec(),
                vtype: winreg::enums::REG_BINARY,
            },
        )?;

        unsafe {
            let _ = SendNotifyMessageW(
                HWND_BROADCAST,
                WM_SETTINGCHANGE,
                WPARAM(0),
                LPARAM(w!("ImmersiveColorSet").as_ptr() as isize),
            );
        }
        Ok(())
    }

    pub fn get_colors(&self) -> Result<UIColors> {
        let settings = &self.settings;
        Ok(UIColors {
            accent_darkest: winrt_to_self(settings.GetColorValue(UIColorType::AccentDark3)?),
            accent_darker: winrt_to_self(settings.GetColorValue(UIColorType::AccentDark2)?),
            accent_dark: winrt_to_self(settings.GetColorValue(UIColorType::AccentDark1)?),
            accent: winrt_to_self(settings.GetColorValue(UIColorType::Accent)?),
            accent_light: winrt_to_self(settings.GetColorValue(UIColorType::AccentLight1)?),
            accent_lighter: winrt_to_self(settings.GetColorValue(UIColorType::AccentLight2)?),
            accent_lightest: winrt_to_self(settings.GetColorValue(UIColorType::AccentLight3)?),
            // https://learn.microsoft.com/is-is/uwp/api/windows.ui.viewmanagement.uisettings.getcolorvalue?view=winrt-19041#remarks
            complement: Color::default(),
        })
    }
}

impl Drop for SystemSettings {
    fn drop(&mut self) {
        if let Some(token) = self.color_event_token.take() {
            self.settings.RemoveColorValuesChanged(token).log_error();
        }

        if let Some(deferral) = self.text_scale_event_token.take() {
            self.settings
                .RemoveTextScaleFactorChanged(deferral)
                .log_error();
        }
    }
}
