use std::sync::LazyLock;

use crate::{
    error::{Result, ResultLogExt},
    event_manager,
};
use seelen_core::system_state::{Color, UIColors};
use windows::{
    Foundation::TypedEventHandler,
    UI::ViewManagement::{UIColorType, UISettings},
};
use windows_core::IInspectable;

fn winrt_to_self(color: windows::UI::Color) -> Color {
    Color {
        r: color.R,
        g: color.G,
        b: color.B,
        a: color.A,
    }
}

fn rgb_to_hsl(r: u8, g: u8, b: u8) -> (f64, f64, f64) {
    let r = r as f64 / 255.0;
    let g = g as f64 / 255.0;
    let b = b as f64 / 255.0;
    let max = r.max(g).max(b);
    let min = r.min(g).min(b);
    let l = (max + min) / 2.0;
    if max == min {
        return (0.0, 0.0, l);
    }
    let delta = max - min;
    let s = if l > 0.5 {
        delta / (2.0 - max - min)
    } else {
        delta / (max + min)
    };
    let h = if max == r {
        ((g - b) / delta + if g < b { 6.0 } else { 0.0 }) / 6.0
    } else if max == g {
        ((b - r) / delta + 2.0) / 6.0
    } else {
        ((r - g) / delta + 4.0) / 6.0
    };
    (h * 360.0, s, l)
}

fn hue_to_rgb(p: f64, q: f64, t: f64) -> f64 {
    let t = if t < 0.0 {
        t + 1.0
    } else if t > 1.0 {
        t - 1.0
    } else {
        t
    };
    if t < 1.0 / 6.0 {
        p + (q - p) * 6.0 * t
    } else if t < 0.5 {
        q
    } else if t < 2.0 / 3.0 {
        p + (q - p) * (2.0 / 3.0 - t) * 6.0
    } else {
        p
    }
}

fn hsl_to_rgb(h: f64, s: f64, l: f64) -> (u8, u8, u8) {
    if s == 0.0 {
        let v = (l * 255.0).round() as u8;
        return (v, v, v);
    }
    let q = if l < 0.5 {
        l * (1.0 + s)
    } else {
        l + s - l * s
    };
    let p = 2.0 * l - q;
    let hn = h / 360.0;
    let r = hue_to_rgb(p, q, hn + 1.0 / 3.0);
    let g = hue_to_rgb(p, q, hn);
    let b = hue_to_rgb(p, q, hn - 1.0 / 3.0);
    (
        (r * 255.0).round() as u8,
        (g * 255.0).round() as u8,
        (b * 255.0).round() as u8,
    )
}

/// Generates a 32-byte AccentPalette for the Windows registry.
/// 8 colors × 4 bytes (RGBA), ordered: accent_darkest … accent_lightest, complement.
/// Darker/lighter shades are generated by linearly interpolating lightness
/// from 0.05 → base_lightness (indices 0-3) and base_lightness → 0.95 (indices 3-6).
/// The complement (index 7) is the base color with its hue rotated 180°.
fn generate_accent_palette(color: seelen_core::system_state::Color) -> UIColors {
    let (h, s, l) = rgb_to_hsl(color.r, color.g, color.b);
    let mut palette = [0u8; 32];

    for i in 0usize..7 {
        // index 0 = lightest (accent_lightest), index 6 = darkest (accent_darkest)
        let j = 6 - i;
        let step_l = if j <= 3 {
            let t = j as f64 / 3.0;
            0.15 + t * (l - 0.15)
        } else {
            let t = (j - 3) as f64 / 3.0;
            l + t * (0.85 - l)
        };
        let (r, g, b) = hsl_to_rgb(h, s, step_l);
        let off = i * 4;
        palette[off] = r;
        palette[off + 1] = g;
        palette[off + 2] = b;
        palette[off + 3] = color.a;
    }

    // Complement: hue rotated 180°
    let (r, g, b) = hsl_to_rgb((h + 180.0) % 360.0, s, l);
    palette[28] = r;
    palette[29] = g;
    palette[30] = b;
    palette[31] = color.a;

    UIColors::from_bytes(&palette)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SystemSettingsEvent {
    ColorChanged,
    TextScaleChanged,
}

pub struct SystemSettings {
    settings: UISettings,
    color_event_token: Option<i64>,
    text_scale_event_token: Option<i64>,
}

unsafe impl Send for SystemSettings {}

event_manager!(SystemSettings, SystemSettingsEvent);

impl SystemSettings {
    pub fn instance() -> &'static Self {
        static SYSTEM_SETTINGS: LazyLock<SystemSettings> = LazyLock::new(|| {
            let mut settings = SystemSettings::new();
            settings.init().log_error();
            settings
        });
        &SYSTEM_SETTINGS
    }

    fn new() -> Self {
        Self {
            settings: UISettings::new().expect("Failed to create UISettings"),
            color_event_token: None,
            text_scale_event_token: None,
        }
    }

    fn init(&mut self) -> Result<()> {
        // Register color change event
        // Windows-rs clones the handler internally, so we don't need to store it
        let color_token = self
            .settings
            .ColorValuesChanged(&TypedEventHandler::new(Self::internal_on_colors_change))?;
        self.color_event_token = Some(color_token);

        // Register text scale change event
        let text_scale_token = self
            .settings
            .TextScaleFactorChanged(&TypedEventHandler::new(Self::internal_on_text_scale_change))?;
        self.text_scale_event_token = Some(text_scale_token);

        Ok(())
    }

    fn internal_on_colors_change(
        _listener: windows_core::Ref<UISettings>,
        _args: windows_core::Ref<IInspectable>,
    ) -> windows_core::Result<()> {
        let _ = Self::event_tx().send(SystemSettingsEvent::ColorChanged);
        Ok(())
    }

    fn internal_on_text_scale_change(
        _listener: windows_core::Ref<UISettings>,
        _args: windows_core::Ref<IInspectable>,
    ) -> windows_core::Result<()> {
        let _ = Self::event_tx().send(SystemSettingsEvent::TextScaleChanged);
        Ok(())
    }

    pub fn set_accent_color(color: seelen_core::system_state::Color) -> Result<()> {
        use windows::Win32::{
            Foundation::{LPARAM, WPARAM},
            UI::WindowsAndMessaging::{SendNotifyMessageW, HWND_BROADCAST, WM_SETTINGCHANGE},
        };
        use windows_core::w;
        use winreg::{enums::HKEY_CURRENT_USER, RegKey};

        log::info!(
            "Setting accent color to #{:02X}{:02X}{:02X}{:02X}",
            color.r,
            color.g,
            color.b,
            color.a
        );

        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        let key = hkcu.open_subkey_with_flags(
            r"Software\Microsoft\Windows\CurrentVersion\Explorer\Accent",
            winreg::enums::KEY_SET_VALUE,
        )?;
        // Registry stores the accent color as 0xAABBGGRR
        let dword: u32 = u32::from_be_bytes([color.a, color.b, color.g, color.r]);
        key.set_value("AccentColor", &dword)?;
        key.set_value("AccentColorMenu", &dword)?;
        key.set_value("StartColorMenu", &dword)?;

        let palette = generate_accent_palette(color);
        key.set_raw_value(
            "AccentPalette",
            &winreg::RegValue {
                bytes: palette.to_bytes().to_vec(),
                vtype: winreg::enums::REG_BINARY,
            },
        )?;

        unsafe {
            let _ = SendNotifyMessageW(
                HWND_BROADCAST,
                WM_SETTINGCHANGE,
                WPARAM(0),
                LPARAM(w!("ImmersiveColorSet").as_ptr() as isize),
            );
        }
        Ok(())
    }

    pub fn get_colors(&self) -> Result<UIColors> {
        let settings = &self.settings;
        Ok(UIColors {
            accent_darkest: winrt_to_self(settings.GetColorValue(UIColorType::AccentDark3)?),
            accent_darker: winrt_to_self(settings.GetColorValue(UIColorType::AccentDark2)?),
            accent_dark: winrt_to_self(settings.GetColorValue(UIColorType::AccentDark1)?),
            accent: winrt_to_self(settings.GetColorValue(UIColorType::Accent)?),
            accent_light: winrt_to_self(settings.GetColorValue(UIColorType::AccentLight1)?),
            accent_lighter: winrt_to_self(settings.GetColorValue(UIColorType::AccentLight2)?),
            accent_lightest: winrt_to_self(settings.GetColorValue(UIColorType::AccentLight3)?),
            // https://learn.microsoft.com/is-is/uwp/api/windows.ui.viewmanagement.uisettings.getcolorvalue?view=winrt-19041#remarks
            complement: Color::default(),
        })
    }
}

impl Drop for SystemSettings {
    fn drop(&mut self) {
        if let Some(token) = self.color_event_token.take() {
            self.settings.RemoveColorValuesChanged(token).log_error();
        }

        if let Some(deferral) = self.text_scale_event_token.take() {
            self.settings
                .RemoveTextScaleFactorChanged(deferral)
                .log_error();
        }
    }
}
