const _languageList = [
  { label: 'Deutsch', enLabel: 'German', value: 'de' },
  { label: 'English', enLabel: 'English', value: 'en' },
  { label: 'Español', enLabel: 'Spanish', value: 'es' },
  { label: '한국어', enLabel: 'Korean', value: 'ko' },
  { label: '中文', enLabel: 'Chinese', value: 'zh' },
  { label: 'Français', enLabel: 'French', value: 'fr' },
  { label: 'العربية', enLabel: 'Arabic', value: 'ar' },
  { label: 'Português', enLabel: 'Portuguese', value: 'pt' },
  { label: 'Русский', enLabel: 'Russian', value: 'ru' },
  { label: 'हिन्दी', enLabel: 'Hindi', value: 'hi' },
  { label: '日本語', enLabel: 'Japanese', value: 'ja' },
  { label: 'Italiano', enLabel: 'Italian', value: 'it' },
  { label: 'Nederlands', enLabel: 'Dutch', value: 'nl' },
  { label: 'Türkçe', enLabel: 'Turkish', value: 'tr' },
  { label: 'Polski', enLabel: 'Polish', value: 'pl' },
  { label: 'Українська', enLabel: 'Ukrainian', value: 'uk' },
  { label: 'Ελληνικά', enLabel: 'Greek', value: 'el' },
  { label: 'עברית', enLabel: 'Hebrew', value: 'he' },
  { label: 'Svenska', enLabel: 'Swedish', value: 'sv' },
  { label: 'Norsk', enLabel: 'Norwegian', value: 'no' },
  { label: 'Suomi', enLabel: 'Finnish', value: 'fi' },
  { label: 'Dansk', enLabel: 'Danish', value: 'da' },
  { label: 'Magyar', enLabel: 'Hungarian', value: 'hu' },
  { label: 'Română', enLabel: 'Romanian', value: 'ro' },
  { label: 'Čeština', enLabel: 'Czech', value: 'cs' },
  { label: 'Slovenský', enLabel: 'Slovak', value: 'sk' },
  { label: 'Hrvatski', enLabel: 'Croatian', value: 'hr' },
  { label: 'Български', enLabel: 'Bulgarian', value: 'bg' },
  { label: 'Lietuvių', enLabel: 'Lithuanian', value: 'lt' },
  { label: 'Latviešu', enLabel: 'Latvian', value: 'lv' },
  { label: 'Eesti', enLabel: 'Estonian', value: 'et' },
  { label: 'Filipino', enLabel: 'Filipino', value: 'tl' },
  { label: 'Tiếng Việt', enLabel: 'Vietnamese', value: 'vi' },
  { label: 'ไทย', enLabel: 'Thai', value: 'th' },
  { label: 'Indonesia', enLabel: 'Indonesian', value: 'id' },
  { label: 'Malay', enLabel: 'Malay', value: 'ms' },
  { label: 'Català', enLabel: 'Catalan', value: 'ca' },
  { label: 'Afrikaans', enLabel: 'Afrikaans', value: 'af' },
  { label: 'বাংলা', enLabel: 'Bengali', value: 'bn' },
  { label: 'فارسی', enLabel: 'Farsi', value: 'fa' },
  { label: 'ਪੰਜਾਬੀ', enLabel: 'Punjabi', value: 'pa' },
  { label: 'Kiswahili', enLabel: 'Swahili', value: 'sw' },
  { label: 'தமிழ்', enLabel: 'Tamil', value: 'ta' },
  { label: 'اردو', enLabel: 'Urdu', value: 'ur' },
  { label: 'Cymraeg', enLabel: 'Welsh', value: 'cy' },
  { label: 'አማርኛ', enLabel: 'Amharic', value: 'am' },
  { label: 'Հայերեն', enLabel: 'Armenian', value: 'hy' },
  { label: 'Azərbaycan', enLabel: 'Azerbaijani', value: 'az' },
  { label: 'Euskara', enLabel: 'Basque', value: 'eu' },
  { label: 'Bosanski', enLabel: 'Bosnian', value: 'bs' },
  { label: 'ქართული', enLabel: 'Georgian', value: 'ka' },
  { label: 'ગુજરાતી', enLabel: 'Gujarati', value: 'gu' },
  { label: 'Íslenska', enLabel: 'Icelandic', value: 'is' },
  { label: 'ភាសាខ្មែរ', enLabel: 'Khmer', value: 'km' },
  { label: 'Kurdî', enLabel: 'Kurdish', value: 'ku' },
  { label: 'ລາວ', enLabel: 'Lao', value: 'lo' },
  { label: 'Lëtzebuergesch', enLabel: 'Luxembourgish', value: 'lb' },
  { label: 'Македонски', enLabel: 'Macedonian', value: 'mk' },
  { label: 'Malti', enLabel: 'Maltese', value: 'mt' },
  { label: 'Монгол', enLabel: 'Mongolian', value: 'mn' },
  { label: 'नेपाली', enLabel: 'Nepali', value: 'ne' },
  { label: 'پښتو', enLabel: 'Pashto', value: 'ps' },
  { label: 'Српски', enLabel: 'Serbian', value: 'sr' },
  { label: 'සිංහල', enLabel: 'Sinhala', value: 'si' },
  { label: 'Soomaali', enLabel: 'Somali', value: 'so' },
  { label: 'Тоҷикӣ', enLabel: 'Tajik', value: 'tg' },
  { label: 'తెలుగు', enLabel: 'Telugu', value: 'te' },
  { label: 'Oʻzbek', enLabel: 'Uzbek', value: 'uz' },
  { label: 'Yorùbá', enLabel: 'Yoruba', value: 'yo' },
  { label: 'isiZulu', enLabel: 'Zulu', value: 'zu' },
] as const;

export type SupportedLanguagesCode = (typeof _languageList)[number]['value'];

export interface Language {
  label: string;
  enLabel: string;
  /** language code @example 'de' 'es' 'zh' 'en_us' 'en_uk' */
  value: string;
}

export const SupportedLanguages: Language[] = _languageList.toSorted((a, b) => a.label.localeCompare(b.label));