/**
 * This file is generated by Seelen UI and will be replaced on each update please don't modify manually.
 * If you want to introduce your own implementation for shortcuts with AHK or any other scripting language
 * just disable Seelen UI intergrated shortcuts in the shortcuts tab, and this file will be ignored.
 * 
 * To read more about AHK see: https://www.autohotkey.com/docs/v2
 */
ExitIfDisabled() {
  settingsPath := "C:\Users\" . A_UserName . "\.config\komorebi-ui\settings.json"
  if (FileExist(settingsPath) !== "") {
    htmlfile := ComObject('htmlfile')
    htmlfile.write('<meta http-equiv="X-UA-Compatible" content="IE=edge">')
    settings := htmlfile.parentWindow.JSON.parse(FileRead(settingsPath))
    if (settings.ahk_enabled !== true) {
      ExitApp()
    }
    settings := ""
  }
}


global seelen := "Seelen UI.exe"
Reserve(reservation) {
  RunWait(seelen " wm reserve " reservation, , "Hide")
}

CancelReservation() {
  RunWait(seelen " wm cancel-reservation", , "Hide")
}

WMDebug() {
  RunWait(seelen " wm debug", , "Hide")
}