/*
 * This file is generated by Seelen UI and will be replaced on each update please don't modify manually.
 * If you want to introduce your own implementation for shortcuts with AHK or any other scripting language
 * just disable Seelen UI intergrated shortcuts in the shortcuts tab, and this file will be ignored.
*/
#Requires AutoHotkey v2.0
#SingleInstance Force
#NoTrayIcon

#Include seelen.lib.ahk

;Open Webview Development Tools
^+w:: WMDebug()

; Pause Window Manager
^#!p:: {
  PauseWM()
  ExitApp()
}

; Reserve space for the next opened window
>^+w:: Reserve("top")
>^+s:: Reserve("bottom")
>^+a:: Reserve("left")
>^+d:: Reserve("right")

>^+q:: Reserve("float")
>^+e:: Reserve("stack")

~Esc:: {
  CancelReservation()
}

; Focus windows at side
>^w:: focus("up")
>^s:: focus("down")
>^a:: focus("left")
>^d:: focus("right")

>^Enter:: focus("lastest")

; Increase or decrease window size
#!=:: updateWindowWidth("increase")
#!-:: updateWindowWidth("decrease")
#!+=:: updateWindowHeight("increase")
#!+-:: updateWindowHeight("decrease")

#!0:: resetWorkspaceSize()

; Switch workspaces
!1:: SwitchWorkspace(0)
!2:: SwitchWorkspace(1)
!3:: SwitchWorkspace(2)
!4:: SwitchWorkspace(3)
!5:: SwitchWorkspace(4)
!6:: SwitchWorkspace(5)
!7:: SwitchWorkspace(6)
!8:: SwitchWorkspace(7)
!9:: SwitchWorkspace(8)

; Send the focused window across workspaces and switch specified workspace
!+1:: MoveToWorkspace(0)
!+2:: MoveToWorkspace(1)
!+3:: MoveToWorkspace(2)
!+4:: MoveToWorkspace(3)
!+5:: MoveToWorkspace(4)
!+6:: MoveToWorkspace(5)
!+7:: MoveToWorkspace(6)
!+8:: MoveToWorkspace(7)
!+9:: MoveToWorkspace(8)

; Send the focused window across workspaces
#+1:: SendToWorkspace(0)
#+2:: SendToWorkspace(1)
#+3:: SendToWorkspace(2)
#+4:: SendToWorkspace(3)
#+5:: SendToWorkspace(4)
#+6:: SendToWorkspace(5)
#+7:: SendToWorkspace(6)
#+8:: SendToWorkspace(7)
#+9:: SendToWorkspace(8)

/*
TODOS

!+q:: CycleFocus("previous")
!q:: CycleFocus("next")

; Move windows
#+a:: Move("left")
#+s:: Move("down")
#+w:: Move("up")
#+d:: Move("right")

#+Enter:: Promote()

#+x:: FlipLayout("horizontal")
#+z:: FlipLayout("vertical")

; Stack windows
#a:: Stack("left")
#d:: Stack("right")
#w:: Stack("up")
#s:: Stack("down")
#;:: Unstack()

#+q:: CycleStack("previous")
#q:: CycleStack("next")

; Manipulate windows
#f:: ToggleFloat()
#m:: ToggleMonocle()
*/
