export type SupportedLanguagesCode = (typeof SupportedLanguages)[number]["value"];
export interface SupportedLanguage {
  label: string;
  enLabel: string;
  /** language code @example 'de' 'es' 'zh' 'en-US' 'en-UK' */
  value: string;
}

export const SupportedLanguages = [
  { label: "Afrikaans", enLabel: "Afrikaans", value: "af" },
  { label: "አማርኛ", enLabel: "Amharic", value: "am" },
  { label: "العربية", enLabel: "Arabic", value: "ar" },
  { label: "Azərbaycan", enLabel: "Azerbaijani", value: "az" },
  { label: "Български", enLabel: "Bulgarian", value: "bg" },
  { label: "বাংলা", enLabel: "Bengali", value: "bn" },
  { label: "Bosanski", enLabel: "Bosnian", value: "bs" },
  { label: "Català", enLabel: "Catalan", value: "ca" },
  { label: "Čeština", enLabel: "Czech", value: "cs" },
  { label: "Cymraeg", enLabel: "Welsh", value: "cy" },
  { label: "Dansk", enLabel: "Danish", value: "da" },
  { label: "Deutsch", enLabel: "German", value: "de" },
  { label: "Ελληνικά", enLabel: "Greek", value: "el" },
  { label: "English", enLabel: "English", value: "en" },
  { label: "Español", enLabel: "Spanish", value: "es" },
  { label: "Eesti", enLabel: "Estonian", value: "et" },
  { label: "Euskara", enLabel: "Basque", value: "eu" },
  { label: "فارسی", enLabel: "Persian", value: "fa" },
  { label: "Suomi", enLabel: "Finnish", value: "fi" },
  { label: "Français", enLabel: "French", value: "fr" },
  { label: "ગુજરાતી", enLabel: "Gujarati", value: "gu" },
  { label: "עברית", enLabel: "Hebrew", value: "he" },
  { label: "हिन्दी", enLabel: "Hindi", value: "hi" },
  { label: "Hrvatski", enLabel: "Croatian", value: "hr" },
  { label: "Magyar", enLabel: "Hungarian", value: "hu" },
  { label: "Հայերեն", enLabel: "Armenian", value: "hy" },
  { label: "Indonesia", enLabel: "Indonesian", value: "id" },
  { label: "Íslenska", enLabel: "Icelandic", value: "is" },
  { label: "Italiano", enLabel: "Italian", value: "it" },
  { label: "日本語", enLabel: "Japanese", value: "ja" },
  { label: "ქართული", enLabel: "Georgian", value: "ka" },
  { label: "ភាសាខ្មែរ", enLabel: "Khmer", value: "km" },
  { label: "한국어", enLabel: "Korean", value: "ko" },
  { label: "Kurdî", enLabel: "Kurdish", value: "ku" },
  { label: "Lëtzebuergesch", enLabel: "Luxembourgish", value: "lb" },
  { label: "ລາວ", enLabel: "Lao", value: "lo" },
  { label: "Lietuvių", enLabel: "Lithuanian", value: "lt" },
  { label: "Latviešu", enLabel: "Latvian", value: "lv" },
  { label: "Македонски", enLabel: "Macedonian", value: "mk" },
  { label: "Монгол", enLabel: "Mongolian", value: "mn" },
  { label: "Malay", enLabel: "Malay", value: "ms" },
  { label: "Malti", enLabel: "Maltese", value: "mt" },
  { label: "नेपाली", enLabel: "Nepali", value: "ne" },
  { label: "Nederlands", enLabel: "Dutch", value: "nl" },
  { label: "Norsk", enLabel: "Norwegian", value: "no" },
  { label: "ਪੰਜਾਬੀ", enLabel: "Punjabi", value: "pa" },
  { label: "Polski", enLabel: "Polish", value: "pl" },
  { label: "پښتو", enLabel: "Pashto", value: "ps" },
  { label: "Português (Brasil)", enLabel: "Portuguese (Brazil)", value: "pt-BR" },
  { label: "Português (Portugal)", enLabel: "Portuguese (Portugal)", value: "pt-PT" },
  { label: "Română", enLabel: "Romanian", value: "ro" },
  { label: "Русский", enLabel: "Russian", value: "ru" },
  { label: "සිංහල", enLabel: "Sinhala", value: "si" },
  { label: "Slovenský", enLabel: "Slovak", value: "sk" },
  { label: "Soomaali", enLabel: "Somali", value: "so" },
  { label: "Српски", enLabel: "Serbian", value: "sr" },
  { label: "Svenska", enLabel: "Swedish", value: "sv" },
  { label: "Kiswahili", enLabel: "Swahili", value: "sw" },
  { label: "தமிழ்", enLabel: "Tamil", value: "ta" },
  { label: "తెలుగు", enLabel: "Telugu", value: "te" },
  { label: "Тоҷикӣ", enLabel: "Tajik", value: "tg" },
  { label: "ไทย", enLabel: "Thai", value: "th" },
  { label: "Tagalog", enLabel: "Filipino", value: "tl" },
  { label: "Türkçe", enLabel: "Turkish", value: "tr" },
  { label: "Українська", enLabel: "Ukrainian", value: "uk" },
  { label: "اردو", enLabel: "Urdu", value: "ur" },
  { label: "Oʻzbek", enLabel: "Uzbek", value: "uz" },
  { label: "Tiếng Việt", enLabel: "Vietnamese", value: "vi" },
  { label: "Yorùbá", enLabel: "Yoruba", value: "yo" },
  { label: "中文 (简体)", enLabel: "Chinese (Simplified)", value: "zh-CN" },
  { label: "中文 (繁體)", enLabel: "Chinese (Traditional)", value: "zh-TW" },
  { label: "isiZulu", enLabel: "Zulu", value: "zu" },
] as const;
