/*
 * This file is generated by Seelen UI and will be replaced on each update please don't modify manually.
 * If you want to introduce your own implementation for shortcuts with AHK or any other scripting language
 * just disable Seelen UI integrated shortcuts in the shortcuts tab, and this file will be ignored.
*/
#Requires AutoHotkey v2.0
#SingleInstance Force
#NoTrayIcon

#Include seelen.lib.ahk

CloseIfNotRunning()

; Foreground or run application
;start_weg_app_0
x:: ForegroundOrRun(0)
;start_weg_app_1
x:: ForegroundOrRun(1)
;start_weg_app_2
x:: ForegroundOrRun(2)
;start_weg_app_3
x:: ForegroundOrRun(3)
;start_weg_app_4
x:: ForegroundOrRun(4)
;start_weg_app_5
x:: ForegroundOrRun(5)
;start_weg_app_6
x:: ForegroundOrRun(6)
;start_weg_app_7
x:: ForegroundOrRun(7)
;start_weg_app_8
x:: ForegroundOrRun(8)
;start_weg_app_9
x:: ForegroundOrRun(9)
