/*
 * This file is generated by Seelen UI and will be replaced on each update please don't modify manually.
 * If you want to introduce your own implementation for shortcuts with AHK or any other scripting language
 * just disable Seelen UI integrated shortcuts in the shortcuts tab, and this file will be ignored.
*/
#Requires AutoHotkey v2.0
#SingleInstance Force
#NoTrayIcon

#Include seelen.lib.ahk

CloseIfNotRunning()

;debug_wm
^#!w:: WMDebug()

^#!p:: {
  PauseWM()
  ExitApp()
}

;reserve_top
x:: Reserve("top")
;reserve_bottom
x:: Reserve("bottom")
;reserve_left
x:: Reserve("left")
;reserve_right
x:: Reserve("right")

;reserve_float
x:: Reserve("float")
;reserve_stack
x:: Reserve("stack")

~Esc:: {
  CancelReservation()
}

;focusTop
x:: focus("up")
;focus_bottom
x:: focus("down")
;focus_left
x:: focus("left")
;focus_right
x:: focus("right")

;focus_latest
x:: focus("latest")

; Increase or decrease window size
;increase_width
x:: updateWindowWidth("increase")
;decrease_width
x:: updateWindowWidth("decrease")
;increase_height
x:: updateWindowHeight("increase")
;decrease_height
x:: updateWindowHeight("decrease")

;restore_sizes
x:: resetWorkspaceSize()

; Switch workspaces
;switch_workspace_0
x:: SwitchWorkspace(0)
;switch_workspace_1
x:: SwitchWorkspace(1)
;switch_workspace_2
x:: SwitchWorkspace(2)
;switch_workspace_3
x:: SwitchWorkspace(3)
;switch_workspace_4
x:: SwitchWorkspace(4)
;switch_workspace_5
x:: SwitchWorkspace(5)
;switch_workspace_6
x:: SwitchWorkspace(6)
;switch_workspace_7
x:: SwitchWorkspace(7)
;switch_workspace_8
x:: SwitchWorkspace(8)
;switch_workspace_9
x:: SwitchWorkspace(9)

; Send the focused window across workspaces and switch specified workspace
;move_to_workspace_0
x:: MoveToWorkspace(0)
;move_to_workspace_1
x:: MoveToWorkspace(1)
;move_to_workspace_2
x:: MoveToWorkspace(2)
;move_to_workspace_3
x:: MoveToWorkspace(3)
;move_to_workspace_4
x:: MoveToWorkspace(4)
;move_to_workspace_5
x:: MoveToWorkspace(5)
;move_to_workspace_6
x:: MoveToWorkspace(6)
;move_to_workspace_7
x:: MoveToWorkspace(7)
;move_to_workspace_8
x:: MoveToWorkspace(8)
;move_to_workspace_9
x:: MoveToWorkspace(9)

; Send the focused window across workspaces
;send_to_workspace_0
x:: SendToWorkspace(0)
;send_to_workspace_1
x:: SendToWorkspace(1)
;send_to_workspace_2
x:: SendToWorkspace(2)
;send_to_workspace_3
x:: SendToWorkspace(3)
;send_to_workspace_4
x:: SendToWorkspace(4)
;send_to_workspace_5
x:: SendToWorkspace(5)
;send_to_workspace_6
x:: SendToWorkspace(6)
;send_to_workspace_7
x:: SendToWorkspace(7)
;send_to_workspace_8
x:: SendToWorkspace(8)
;send_to_workspace_9
x:: SendToWorkspace(9)

/*
TODO

!+q:: CycleFocus("previous")
!q:: CycleFocus("next")

; Move windows
#+a:: Move("left")
#+s:: Move("down")
#+w:: Move("up")
#+d:: Move("right")

#+Enter:: Promote()

#+x:: FlipLayout("horizontal")
#+z:: FlipLayout("vertical")

; Stack windows
#a:: Stack("left")
#d:: Stack("right")
#w:: Stack("up")
#s:: Stack("down")
#;:: Unstack()

#+q:: CycleStack("previous")
#q:: CycleStack("next")

; Manipulate windows
#f:: ToggleFloat()
#m:: ToggleMonocle()
*/
