/*
 * This file is generated by Seelen UI and will be replaced on each update please don't modify manually.
 * If you want to introduce your own implementation for shortcuts with AHK or any other scripting language
 * just disable Seelen UI intergrated shortcuts in the shortcuts tab, and this file will be ignored.
*/
#Requires AutoHotkey v2.0
#SingleInstance Force

global seelen := "SEELEN_UI_EXE_PATH"

/** Close the AHK if app is crashed or forced to close */
CloseIfNotRunning() {
  if ProcessExist("seelen-ui.exe") == 0 {
    ExitApp()
  }
  SetTimer(CloseIfNotRunning, 1000)
}

OpenSettings(){
  RunWait(seelen " settings", , "Hide")
}

Reserve(reservation) {
  RunWait(seelen " wm reserve " reservation, , "Hide")
}

CancelReservation() {
  RunWait(seelen " wm cancel-reservation", , "Hide")
}

WMDebug() {
  RunWait(seelen " wm debug", , "Hide")
}

updateWindowWidth(action) {
  RunWait(seelen " wm width " action, , "Hide")
}

updateWindowHeight(action) {
  RunWait(seelen " wm height " action, , "Hide")
}

resetWorkspaceSize() {
  RunWait(seelen " wm reset-workspace-size", , "Hide")
}

focus(action) {
  RunWait(seelen " wm focus " action, , "Hide")
}

SwitchWorkspace(idx) {
  RunWait(seelen " wm switch-workspace " idx, , "Hide")
}

MoveToWorkspace(idx) {
  RunWait(seelen " wm move-to-workspace " idx, , "Hide")
}

SendToWorkspace(idx) {
  RunWait(seelen " wm send-to-workspace " idx, , "Hide")
}

PauseWM() {
  RunWait(seelen " wm pause", , "Hide")
}

/**
 * Resumes the window manager and will start `seelen.wm.ahk` if
 * the included AHK shortcuts are enabled in the settings.
 */
ResumeWM() {
  RunWait(seelen " wm resume", , "Hide")
}

DebugHitboxes() {
  RunWait(seelen " tb debug-hitbox", , "Hide")
  RunWait(seelen " weg debug-hitbox", , "Hide")
}