/*
 * This file is generated by Seelen UI and will be replaced on each update please don't modify manually.
 * If you want to introduce your own implementation for shortcuts with AHK or any other scripting language
 * just disable Seelen UI intergrated shortcuts in the shortcuts tab, and this file will be ignored.
*/
#Requires AutoHotkey v2.0
#SingleInstance Force
#NoTrayIcon

#Include seelen.lib.ahk

CloseIfNotRunning()

; Open Settings
#k:: OpenSettings()

; Resume Window Manager
^#!p:: {
  ResumeWM()
}

^#!l:: {
  ToggleWinEventTracing()
}

^#!t:: {
  ToggleMutexLockTracing()
}

LWin & Space::ToggleAppLauncher()