/*
 * This file is generated by Seelen UI and will be replaced on each update please don't modify manually.
 * If you want to introduce your own implementation for shortcuts with AHK or any other scripting language
 * just disable Seelen UI integrated shortcuts in the shortcuts tab, and this file will be ignored.
*/
#Requires AutoHotkey v2.0
#SingleInstance Force
#NoTrayIcon

#Include seelen.lib.ahk

CloseIfNotRunning()

;debug_wm
^#!w:: WMDebug()

^#!p:: {
  PauseWM()
  ExitApp()
}

;reserve_top
x:: Reserve("top")
;reserve_bottom
x:: Reserve("bottom")
;reserve_left
x:: Reserve("left")
;reserve_right
x:: Reserve("right")

;reserve_float
x:: Reserve("float")
;reserve_stack
x:: Reserve("stack")

~Esc:: {
  CancelReservation()
}

;focusTop
x:: focus("up")
;focus_bottom
x:: focus("down")
;focus_left
x:: focus("left")
;focus_right
x:: focus("right")

;focus_latest
x:: focus("latest")

; Increase or decrease window size
;increase_width
x:: updateWindowWidth("increase")
;decrease_width
x:: updateWindowWidth("decrease")
;increase_height
x:: updateWindowHeight("increase")
;decrease_height
x:: updateWindowHeight("decrease")

;restore_sizes
x:: resetWorkspaceSize()

/*
TODO

!+q:: CycleFocus("previous")
!q:: CycleFocus("next")

; Move windows
#+a:: Move("left")
#+s:: Move("down")
#+w:: Move("up")
#+d:: Move("right")

#+Enter:: Promote()

#+x:: FlipLayout("horizontal")
#+z:: FlipLayout("vertical")

; Stack windows
#a:: Stack("left")
#d:: Stack("right")
#w:: Stack("up")
#s:: Stack("down")
#;:: Unstack()

#+q:: CycleStack("previous")
#q:: CycleStack("next")

; Manipulate windows
#f:: ToggleFloat()
#m:: ToggleMonocle()
*/
